### PR TITLE
Support for v5 async

### PR DESCRIPTION
**Pull request by aviskase**
Several considerations:

1) I've included code from open PR #59 , because now we have same code for attributes and parameters
2) Removed `stop_launch` method --- v2 endpoint only has `finish`
3) Removed `ReportPortalServiceAsync` because client uses only async endpoints
4) I don't like this solution, but I had to introduce two `base_ulr`s, because `get_project_settings` uses v1 endpoint
5) I couldn't find clear explanation about `id` vs `uuid`. But from some discussions it seems like the client should always send `uuid` to start item, yet (1) it's not documented in current API schema (2) seems to work without it. 

Tested on: API Service: 5.0.0-RC-2;Index Service: 5.0.4;Authorization Service: 5.0;Service UI: 5.0.0-RC-3;

### CODE REVIEW

**Comment by aviskase** [comment]
@iivanou yes, I'm aware of incompatibility problem. I've asked about it in the Slack group while experimenting with converting our custom logs to RP v5.0:

image

> The client for RP version 5.0 and above is gonna be written from scratch.

Is there a roadmap of when and how that will be done?

**Comment by iivanou** [comment]
There is no roadmap defined yet. And I don't think it won't due to the nature of this project. We're starting architectural stuff this week, hopefully. If you do need to have these changes being available ASAP, they should go into a separate branch.

**Comment by aviskase** [comment]
NP. It's a bit of miscommunication, based on Slack I figured PR would be helpful. 
I will keep my fork until official rewrite, so that anyone in need to play with v5 could use it.

**Comment by iivanou** [comment]
@aviskase Don't you mind closing this pull request? All these changes are included in #62 with a few additional fixes.

**Comment by aviskase** [comment]
Ok

**Pull request closed without merging**
