### PR TITLE
Add a timeout to HTTP POST connects and reads

### PR DESCRIPTION
**Pull request by rb1**
Both timeout are hardcoded to 10 seconds. Later commits will make this
configurable.

This doesn't put a timeout around _all_ of the HTTP POST requests
in the codebase.

### CODE REVIEW

**Comment by rb1** [comment]
Total noobie here... but this seemed like some low hanging fruit. It's not fully comprehensive, so I hesitate to claim it completely fixes #170, but that is a motivating factor here..

**Review by HardNorth — CHANGES_REQUESTED** [review]
I don't like the idea of setting timeouts on POST requests only. Either on all of the requests, either on none of them.

**Comment by rb1** [comment]
I went with adding timeouts to the GETs as well as the POSTs.

**Review by HardNorth — APPROVED** [review]

**Comment by HardNorth** [comment]
@rb1 Thank you!

**Pull request merged**
